spring.application.name=NotesApp
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=NotesDB;encrypt=true;trustServerCertificate=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=has9
spring.datasource.password=2244
spring.jpa.hibernate.ddl-auto=update
